[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.localnet]
maiker_contracts = "27mwfhSgaW1BDyYHcnfRnthvrCUZefXnwawH2YYbx2xx"

[programs.devnet]
maiker_contracts = "27mwfhSgaW1BDyYHcnfRnthvrCUZefXnwawH2YYbx2xx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keys/private/devnet-deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
